apiVersion: v1
kind: Pod
metadata:
  name: charnley
spec:
  containers:
    - name: mariadb
      image: docker.io/library/mariadb:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: charnley
        - name: MYSQL_USER
          value: charnley
        - name: MYSQL_PASSWORD
          value: charnley
      ports:
        - containerPort: 3306

    - name: phpmyadmin
      image: docker.io/library/phpmyadmin:latest
      env:
        - name: PMA_HOST
          value: mariadb
        - name: PMA_PORT
          value: "3306"
      ports:
        - containerPort: 80
          hostPort: 8080

    - name: laravel
      image: docker.io/bitnami/laravel:latest
      workingDir: /app
      volumeMounts:
        - mountPath: /app
          name: volumen
      command: ["/bin/sh"]
      args:
        - -c
        - |
          if [ ! -f vendor/autoload.php ]; then
            composer install && \
            php artisan key:generate && \
            php artisan migrate
          fi
          php artisan serve --host=0.0.0.0 --port=8000
      ports:
        - containerPort: 8000
          hostPort: 8000

    - name: node
      image: docker.io/library/node:latest
      workingDir: /app
      volumeMounts:
        - mountPath: /app
          name: volumen
      command: ["/bin/sh"]
      args:
        - -c
        - |
          if [ ! -d node_modules ]; then
            npm install
          fi
          npm run dev
      ports:
        - containerPort: 5000
          hostPort: 5000

  volumes:
    - name: volumen
      hostPath:
        path: /changeme